version: '3.8'

services:
  # Baza danych PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: cv-analyzer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cv_analyzer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (FastAPI)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cv-analyzer-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/cv_analyzer
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=False
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/sample_data:/app/sample_data
    ports:
      - "8000:8000"

  # Frontend (React)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: cv-analyzer-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
